version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "crud"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-63wfp8u17xot"
s3_prefix = "crud"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
